spring:
  profiles:
    active: dev

---
server:
  port: 8001

#Mybatis的配置
mybatis:
  type-aliases-package: info.info.lostred.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#Spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-provider #集群应用名保持一致，因为Ribbon通过应用名来访问服务
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&charactorEncoding=utf-8
    username: root
    password: levyteng952786

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01:7001/eureka/,http://eureka-server-02:7002/eureka/,http://eureka-server-03:7003/eureka/
  instance:
    #修改实例的状态描述信息
    instance-id: springcloud-provider-01-8001
    #显示IP地址
    prefer-ip-address: true
#info信息
info:
  app.name: springcloud-example
  company.name: ylz


---
server:
  port: 8001

#Mybatis的配置
mybatis:
  type-aliases-package: info.info.lostred.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#Spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-provider #集群应用名保持一致，因为Ribbon通过应用名来访问服务
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&charactorEncoding=utf-8
    username: root
    password: levyteng952786

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01:7001/eureka/,http://eureka-server-02:7002/eureka/,http://eureka-server-03:7003/eureka/
  instance:
    #修改实例的状态描述信息
    instance-id: springcloud-provider-01-8001
    #显示IP地址
    prefer-ip-address: true
#info信息
info:
  app.name: springcloud-example
  company.name: ylz
