spring:
  profiles: 
    active: dev

---
server:
  port: 8201
#Spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider #集群应用名保持一致，因为Ribbon通过应用名来访问服务

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01:7001/eureka/,http://eureka-server-02:7002/eureka/,http://eureka-server-03:7003/eureka/

---
server:
  port: 8202
#Spring的配置
spring:
  profiles: test
  application:
    name: springcloud-provider #集群应用名保持一致，因为Ribbon通过应用名来访问服务

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01:7001/eureka/,http://eureka-server-02:7002/eureka/,http://eureka-server-03:7003/eureka/

